version: "3.1"

services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8090:8080"

networks:
  default:
    name: docker_default